import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)



// const sidebars: SidebarsConfig = {
//   维基建设: {
//     维基建设:[{type: 'autogenerated', dirName: 'wiki-build-guide'}]
//   },
// };

import docFiles from "./docs"

let sidebars = {}

docFiles.forEach(v=>{
  if(v.noSidebar) {
    return
  }
  sidebars[v.displayName] = {
    [v.displayName] : [
      {
        type: 'autogenerated',
        dirName: v.dirName
      }
    ]
  }
})

export default sidebars;
